.github/workflows/build.yml, ci-manifest.yml
This builds the application using one of the Github workflows.
=> workflow: Create basic build

.github/workflows/build.yml, main.c, tests/time/CMakeLists.txt, tests/time/Cargo.toml, tests/time/prj.conf, tests/time/src/lib.rs, tests/time/src/times.c, tests/time/testcase.yaml, zephyr-sys/build.rs, zephyr/Cargo.toml, zephyr/module.yml, zephyr/src/lib.rs, zephyr/src/sys.rs, zephyr/src/time.rs
This is a migration of the open PR zephyrproject-rtos/zephyr#78193. To the module version. The only changes from that PR are the squashing a few of the fixup commits.
=> Add Duration and Instant support to Rust.

CMakeLists.txt
The Zephyr PR https://github.com/zephyrproject-rtos/zephyr/pull/78320 clean up and improves link handling in Zephyr.
One improvement is the deterministic and correct link location of runtime and C library linking at the end of link arguments to ensure all libraries are able to use standard functions.
However the librustapp.a library created by the cargo tool also contains runtime functions. It would in most cases be considered correct that a library, such as librustapp.a, which provides functions are linked first so that those functions provided as part of rust toolchain takes precedence over the runtime library provided by the C / C++ toolchain.
However on the riscv32 / riscv64 architecture the rust prebuilt libraries makes use of relocation types in the clzsi2 object which are unknown …
=> cmake: linking app with runtime library together with rust app library

zephyr/src/sys/thread.rs
Two things here:  One is an important fix to `Thread::spawn` which makes it safe against multiple spawns of the same thread.
The other is to add a method to set the name of the thread.
=> Fixes to Thread

.github/workflows/build.yml, Kconfig, samples/hello_world/sample.yaml, tests/time/testcase.yaml
The code conditionally compiles against building on systems with dynami timers.  Until this support can be added, be sure to not define `RUST_SUPPORTED` on these targets.
=> cmake: Avoid appearing to support targets with dynamic timers

main.c, samples/hello_world/Cargo.toml, samples/hello_world/prj.conf, samples/hello_world/src/lib.rs, zephyr-sys/build.rs, zephyr-sys/wrapper.h, zephyr/Cargo.toml, zephyr/src/lib.rs, zephyr/src/logging.rs, zephyr/src/logging/impl_printk.rs, zephyr/src/logging/impl_zlog.rs, zephyr/src/sys/queue.rs, zephyr/src/sys/sync/mutex.rs, zephyr/src/sys/sync/semaphore.rs
This implements three simplistic log handlers when running on top of Zephyr. All of these are built around the string formatting `log` crate, and as such will have a noticeable impact on code size, as well as stack usage for any thread that is logging.
The three handlers are:
- none: Messages logged through `log::info!()` and friends are discarded.
- printk: Messages are logged directly through the printk mechanism.  This is selected if either `CONFIG_LOG` is disabled or if `CONFIG_LOG_MODE_MINIMAL` is selected.
- zlog: Logs messages through Zephyr's logging framework. Rather than trying to decipher the maze of twisty macros of Zephyr's logging, this logs into an allocated string, and submits the message via Zephyr's regular log macros.
Think of this as more of a stop-gap to get some kind …
=> Create some log handlers between Rust and the Zephyr world

zephyr-sys/build.rs, zephyr-sys/wrapper.h
Add bt_ APIs to the generated bindings to enable bluetooth application development.
=> Add bt_ APIs to the generated bindings

CMakeLists.txt
Use the Zephyr KConfig `CONFIG_DEBUG` to determine if the Rust code should be built as release or debug.  This will better optimize the code.
Applications can still set options for `[profile.release]` to enable things such as run time assertions.  For example, debug symbols can still be enabled with `debug = "full"`, which attempts to insert debugging information, although the optimizer can still make the code challenging to debug.o
`debug-assertions = true`, and `overflow-checks = true` can still be enabled in the release builds, for some additional checks.
=> cmake: Set the release/debug based on Kconfig

.github/workflows/build.yml, samples/philosophers/Kconfig, samples/philosophers/sample.yaml, samples/philosophers/src/channel.rs, zephyr/src/sync/channel.rs, zephyr/src/sys/queue.rs
Whereas the existing unbounded channels perform an allocation for each message sent, these bounded channels do a single allocation on initialization (of the channel, the zephyr queues used to implement it do an allocation). This allows send to block as well as recv.
This is the first part, coming soon will be send and receive with a timeout. This will allow using bounded channels from irq context (with no timeout).
Fixes #34
=> Implement Bounded channels

tests/timer/CMakeLists.txt, tests/timer/Cargo.toml, tests/timer/prj.conf, tests/timer/src/lib.rs, tests/timer/testcase.yaml, zephyr-sys/src/lib.rs, zephyr/src/lib.rs, zephyr/src/sync/spinmutex.rs, zephyr/src/sys.rs, zephyr/src/sys/queue.rs, zephyr/src/timer.rs
Add a set of wrappers for Zephyr's timer.  Timers start as `StoppedTimer`, which can be either dynamic or static (through object). This can then be started either with `start_simple` or `start_callback` which will return a `SimpleTimer` or a `CallbackTimer`.  This can then be turned back into stopped timers with a `stop` method.
=> zephyr: sys: Create Timer

README.rst, docgen/Cargo.toml, samples/hello_world/Cargo.toml, samples/philosophers/Cargo.toml, tests/time/Cargo.toml, tests/timer/Cargo.toml, zephyr-build/Cargo.toml, zephyr-sys/Cargo.toml, zephyr/Cargo.toml
An earlier change updated all of the crate version numbers to match a Zephyr release.  This is problematic for several reasons:
- Zephyr releases don't correlate with semantic versions.  In general, it is probably best to assume every Zephyr release is a semantic change, and should have a major version bump.
- Cargo does make some assumptions about the meaning of semantic versions (for example, that it can use a version that would be considered semantically equivalent.
- The Rust support consists of multiple crates, and there is no particular reason to tie the version numbers of those together.
At this point, the Rust support for Zephyr is experimental, and definitely needs a 0.x.y version number.  Revert everything back to 0.1.0.  As this stabilizes more, we can start to come up with …
=> Move to semantic versioning

samples/philosophers/src/channel.rs, samples/philosophers/src/dynsemsync.rs, samples/philosophers/src/semsync.rs, zephyr-build/src/devicetree.rs, zephyr-build/src/devicetree/augment.rs, zephyr-build/src/devicetree/output.rs, zephyr-build/src/devicetree/parse.rs, zephyr-build/src/lib.rs, zephyr-sys/src/lib.rs, zephyr/src/align.rs, zephyr/src/device/gpio.rs, zephyr/src/logging/impl_printk.rs, zephyr/src/object.rs, zephyr/src/sync/mutex.rs, zephyr/src/sys/queue.rs, zephyr/src/sys/thread.rs, zephyr/src/timer.rs
This series (based on top of the rustfmt changes in #43, fixes the suggestions given by running clippy.
Clippy can be run on Zephyr rust code with `env RUSTC_WRAPPER=clippy-driver west build`.
=> Clippy updates

samples/blinky/sample.yaml, samples/philosophers/sample.yaml
Without explicitly declaring the need for Rust support, twister tries to build these samples on targest that don't yet support Rust.  Include the filter, as well as an explicit platform allow of the supported targets.
=> samples: Properly filter samples by supported Rust targets

.github/workflows/docs.yml, docs/top-index.html, etc/add-hash.py
This modifies the doc generation workflow to have different behavior on pull requests and on pushes to 'main'.
- For pull requests, the docs are pushed to s3, similar to before.
- For pushes to 'main', the docs are generated, and then used to replace the current docs in gh-pages. This way, gh-pages should always hold the current docs.
=> github: workflow: docs: Push 'main' docs to gh-pages

etc/platforms.txt, samples/bench/sample.yaml, samples/blinky/sample.yaml, samples/hello_world/sample.yaml, samples/philosophers/sample.yaml, samples/work-philosophers/sample.yaml, tests/time/testcase.yaml, tests/timer/testcase.yaml, zephyr/src/printk.rs
Currently, the smp targets seem to be deadlocking immediately on the first critical section.  For this release, disable these targets, and this can be investigated for the next release.
=> samples/tests: Disable the smp targets

docs/top-index.html, zephyr/src/lib.rs
Include a summary of functionality available, with links to the relevant pages.
=> zephyr: Expound upon the rustdoc docs in the source.

samples/embassy/CMakeLists.txt, samples/embassy/Cargo.toml, samples/embassy/pimoroni_tiny_2040.conf, samples/embassy/prj.conf, samples/embassy/rpi_pico.conf, samples/embassy/sample.yaml, samples/embassy/src/lib.rs, zephyr/Cargo.toml, zephyr/src/embassy.rs, zephyr/src/embassy/executor.rs, zephyr/src/embassy/time_driver.rs, zephyr/src/lib.rs
These changes add the ability to use the executor from [Embassy](https://embassy.dev/) on Zephyr. For the most part, Embassy's executor and associated utilities (embassy-time, embassy-sync, embassy-futures) are fairly platform agnostic. This support adds the two things needed to make this all work on Zephyr:
- time-driver. Enabling this feature will use a Zephyr timer to implement the `embassy-timer-driver`, so that all of the time related utilities from `embassy-time` work. There is a bit of challenge here as the embassy utilities expect the tick rate to be set via a feature, and in Zephyr this comes through Kconfig. But, once set correctly, the result should be seamless.
- executor-zephyr. Implements an `Executor` that works just like `embassy-executor`'s built in Executor type, except …
=> Initial support for using Embassy with Rust on Zephyr

zephyr-build/src/devicetree/dts.pest
see: https://github.com/zephyrproject-rtos/zephyr-lang-rust/issues/68
=> Added "\r" to WHITESPACE char for windows build.

samples/blinky/sample.yaml, tests/drivers/gpio-async/testcase.yaml
- Ensure each test/sample has a name distinct from all samples/tests in Zephyr.
- Remove an invalid integration platform from a test. Until this target is supported, don't try the integration test.
=> Fix two issues with samples/tests affecting CI

zephyr/src/embassy.rs, zephyr/src/embassy/executor.rs
Fixes a potential race condition in the suspend/resume sequence.
=> zephyr:embassy: Use a semaphore for the executor

CMakeLists.txt
Otherwise the CMake output is just stuck at the rust build step for
however long it takes to build.
Signed-Off-By: Johannes Schilling <github@deaktualisierung.org>
=> cmake: add USES_TERMINAL to show cargo output

.github/workflows/build.yml, .github/workflows/docs.yml
There are occasionally setup failures that happen with some of the github worker images using python 3.11.  Fix this by always using 3.12 of python.
=> CI: Force python version 3.12

zephyr/src/lib.rs
DT nodes that have addresses with hex letters in them will generate names with capital letters inside the name, which will trigger the `non_snake_case` lint in the compiler.  Pre-emptively allow these names in the devicetree, as this will show up as new targets are added.
=> zephyr: devicetree: Allow non-snake-case names in DT nodes

CMakeLists.txt, zephyr/src/embassy.rs, zephyr/src/lib.rs, zephyr/src/object.rs, zephyr/src/sync.rs, zephyr/src/work.rs
Fix the 'rustdoc' cmake target to have proper dependencies, so that it can be built without having done a full build first.
In addition, fix some documentation warnings that have shown up with the doc runs not having been run.
=> Fix CI problem with doc generation

dt-rust.yaml, zephyr-build/src/devicetree/augment.rs
The Serde "tag" rules was being used for enums, which results in enums being generated in a somewhat awkward format.  Remove this, and change the syntax of the dt-rust.yaml file to match.  This typically results in changes like:
- type: instance
value:
raw:
type: myself
to be simplified to just:
- !Instance
raw: !Myself
=> zephyr-build: Simplify dt-yaml syntax

zephyr/Cargo.toml
To allow the 2024 edition of Rust to be used, one of our macros needs a new syntax, introduced in Rust 1.85 to declare that it is known that the macro expansion is unsafe.
This could work without the minimum rust version, as long as the macro isn't used, but is needed for tests, and Rust stable has already moved to 1.86, so it isn't an onerous requirement.
=> zephyr: Specify minimum rust version

zephyr-sys/build.rs, zephyr-sys/wrapper.h, zephyr/src/sys.rs
There is a fairly fundamental incompatibility between Zephyr spin locks and the Critical Section specification.  Zephyr spin locks do not allow nesting from within a single spin lock.  The critical section API only has an `acquire` and `release` entry, and provides no way (such as a stack frame) to have a unique context for different invocation places.
Unfortunately, this means we cannot use spin locks for critical sections.
Instead, this change implements critical sections using irq locking. The implementation of these macros on Zephyr does try to make them SMP safe, with a simple atomic lock, but there is still something preventing the riscv SMP from working.
Also, these entries cannot be called from user mode.  There are various other reasons we don't support usermode, so at this time, …
=> zephyr: Replace critical-section implementation

zephyr/src/thread.rs
Replace how Zephyr threads are declared in Rust. Provides a proc-macro to make this fairly straightforward:
```rust
#[zephyr::thread(stack_size = MY_STACK_SIZE)]
fn my_thread(arg1: u32, arg2: MyType) { ... }
```
This function can then be called, and will return a `ReadThread`. This has methods for setting priority, and a `start` method, which returns a `RunningThread`, which has a join method. The thread can be respawned after it has exited.
The thread macro also accepts a `pool_size = nnn` parameter, which will create an array of threads, and can be started that many times.
=> Implement a proc-macros threads creation

zephyr-build/src/devicetree/dts.pest
Add support for comments in devicetree source files by extending the existing parser grammar. This is currently required to allow CI to pass on zephyrproject-rtos/zephyr#89410. 
I have zero experience on Rust, but the `COMMENT =` syntax is taken verbatim from an example on the [Pest website](https://pest.rs/book/grammars/syntax.html#implicit-whitespace), and I also tried the change on the live editor there, so... I'm pretty hopeful :slightly_smiling_face:
EDIT: CI passed on the manifest update PR (see message below)
=> dts.pest: Add support for comments in devicetree source files

CMakeLists.txt
Using GENERATE instead of WRITE expands generator expressions.
=> fix(cmake): Evaluate generator expressions in sample cargo config

.github/workflows/build.yml, .github/workflows/docs.yml
This should match the version running in the main zephyr repo.
=> CI: Use specific version of action-zephyr-setup

zephyr-sys/build.rs, zephyr/src/work.rs
Structs in the C world assume zero initialization, and therefore adding fields is not considered an API change.  Support this for an upcoming API change in the work queue config, by deriving default for these structs, and using this zero-init as a default.  This should support fields being added to this struct. The rust code will zero init the unknown fields, which will have the same behavior as the C code.
This should allow zephyr#88345 to be merged, as well as allow the Rust code to work both before and after this change.
=> zephyr: work: Allow struct to have a additional fields

samples/blinky/src/lib.rs, zephyr-sys/src/lib.rs, zephyr/src/device/gpio.rs
Simplify the GPIO driver, by removing the token. This relies on the underlying gpio driver being thread safe. Keep the `get_instance` as unsafe, as this can't be determined statically.
=> Remove the `GpioToken` entirely

.github/workflows/docs.yml
When running CI on pull requests, the S3 keys needed to push doc changes are only accessible when the pull request comes from the same repo as the project repo.  If it is from a clone, these are not available, and the push fails.
Work around this by correctly detecting this case, and avoiding the s3 push in these instances.
As we get more and more outside contributions, this will need to be revisited, possibly with a separate workflow that runs in a different context and has the keys available.
=> ci: Only try to push to s3 for same-repo pull requests

dt-rust.yaml
Augment flash controllers with their instance on STM32
[davidb: minor fixups for 'main']
=> dt-rust.yaml: Add STM32 flash controller
